name: Tests
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  unit-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - name: Checkout Repository And Submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Install Pydivsufsort And Other Dependencies
        run: |
          python -m pip install -r requirements.txt
          git submodule init
          git submodule update

          mkdir tempbuild
          cd tempbuild
          cmake -DBUILD_DIVSUFSORT64=ON -DBUILD_EXAMPLES=OFF -DUSE_OPENMP=ON $PLATFORM_OPTION ../libdivsufsort
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmake --build . --config Release
            OUTPATH="tempbuild/examples/Release/divsufsort"
          else
            make
            OUTPATH="tempbuild/lib/libdivsufsort"
          fi

          cd ..

          # copy the two largest files, aka the dll of divsufsort and divsufsort64
          mv $(du $OUTPATH* | sort -nr | head -n2 | cut -f2) pydivsufsort
          rm -rf tempbuild
          python -m pip install .
        shell: bash
      - name: Run Unit Tests
        run: |
          python -m pip install pytest
          pytest
        shell: bash
